version: '3.7'

services:
  python-app:
    build:
      context: ./python/
    restart: unless-stopped
    depends_on:
      - mysql

  go-app:
    build:
      context: ./go/
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 3000:80
    depends_on:
      - python-app
      - go-app

volumes:
  db-data:
    name: my-db-data
