version: '3.7'

services:
  python-app:
    build:
      context: ./python/
    restart: unless-stopped
    ports:
      - 5000:5000

  go-app:
    build:
      context: ./go/
    restart: unless-stopped
    ports:
      - 8000:8000
