version: '3.7'

services:
  python-app:
    build:
      context: ./python/
    restart: unless-stopped

  go-app:
    build:
      context: ./go/
    restart: unless-stopped

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 3000:80
    depends_on:
      - python-app
      - go-app
